### ISSUE TITLE
uumai-crawler report failure

### ISSUE THREAD

**Issue by gitGksgk** [kanxg/fengchao#1]
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
have git & maven installed under windows
[INFO] uumai-mongo-client ................................. SUCCESS [  0.365 s]
[INFO] uumai-core ......................................... SUCCESS [  0.006 s]
[INFO] uumai-crawler-core ................................. FAILURE [  1.652 s]
[INFO] uumai-crawler-quartz ............................... SKIPPED
[INFO] uumai-distribute-sys ............................... SKIPPED
[INFO] uumai-mapreduce .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.530 s
[INFO] Finished at: 2017-09-05T14:30:25+08:00
[INFO] Final Memory: 41M/376M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project uumai-crawler-core: Compilation failure: Compilation failure:
[ERROR] /C:/Users/this/fengchao/fengchao/uumai-core/crawler-core/src/main/java/com/uumai/crawer2/download/httpclient/HttpConnectionManager.java:[29,11] ▒޷▒▒▒▒▒org.apache.http.pool.ConnPoolControl
[ERROR] ▒Ҳ▒▒▒org.apache.http.pool.ConnPoolControl▒▒▒▒▒ļ▒
[ERROR] /C:/Users/this/fengchao/fengchao/uumai-core/crawler-core/src/main/java/com/uumai/crawer2/download/httpclient/HttpConnectionManager.java:[54,42] ▒޷▒▒▒▒▒org.apache.http.protocol.HttpCoreContext
[ERROR] ▒Ҳ▒▒▒org.apache.http.protocol.HttpCoreContext▒▒▒▒▒ļ▒
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :uumai-crawler-core

**Comment by kanxg** [comment]
looks like you are running in windows , could you add -X and show me the error log

**Comment by gitGksgk** [comment]
yes and i'm installing it via git-bash. here's the log and many thanks for your help; maven version 3.3.9
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/this/fengchao/fengchao/uumai-core/crawler-core/src/main/java/com/uumai/crawer2/download/httpclient/HttpConnectionManager.java:[29,11] ▒޷▒▒▒▒▒org.apache.http.pool.ConnPoolControl
  ▒Ҳ▒▒▒org.apache.http.pool.ConnPoolControl▒▒▒▒▒ļ▒
[ERROR] /C:/Users/this/fengchao/fengchao/uumai-core/crawler-core/src/main/java/com/uumai/crawer2/download/httpclient/HttpConnectionManager.java:[54,42] ▒޷▒▒▒▒▒org.apache.http.protocol.HttpCoreContext
  ▒Ҳ▒▒▒org.apache.http.protocol.HttpCoreContext▒▒▒▒▒ļ▒
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] uumai-fengchao-parent .............................. SUCCESS [  0.703 s]
[INFO] uumai-common ....................................... SUCCESS [  0.010 s]
[INFO] uumai-libs ......................................... SUCCESS [  8.936 s]
[INFO] uumai-crawler-xsoup ................................ SUCCESS [  2.149 s]
[INFO] uumai-zookeeper-client ............................. SUCCESS [  0.487 s]
[INFO] uumai-crawler-util ................................. SUCCESS [  0.711 s]
[INFO] uumai-redis-client ................................. SUCCESS [  0.837 s]
[INFO] uumai-activemq-client .............................. SUCCESS [  1.085 s]
[INFO] uumai-kafka-client ................................. SUCCESS [  0.771 s]
[INFO] uumai-mongo-client ................................. SUCCESS [  0.468 s]
[INFO] uumai-core ......................................... SUCCESS [  0.005 s]
[INFO] uumai-crawler-core ................................. FAILURE [  3.299 s]
[INFO] uumai-crawler-quartz ............................... SKIPPED
[INFO] uumai-distribute-sys ............................... SKIPPED
[INFO] uumai-mapreduce .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.658 s
[INFO] Finished at: 2017-09-06T15:42:15+08:00
[INFO] Final Memory: 42M/313M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project uumai-crawler-core: Compilation failure: Compilation failure:
[ERROR] /C:/Users/this/fengchao/fengchao/uumai-core/crawler-core/src/main/java/com/uumai/crawer2/download/httpclient/HttpConnectionManager.java:[29,11] ▒޷▒▒▒▒▒org.apache.http.pool.ConnPoolControl
[ERROR] ▒Ҳ▒▒▒org.apache.http.pool.ConnPoolControl▒▒▒▒▒ļ▒
[ERROR] /C:/Users/this/fengchao/fengchao/uumai-core/crawler-core/src/main/java/com/uumai/crawer2/download/httpclient/HttpConnectionManager.java:[54,42] ▒޷▒▒▒▒▒org.apache.http.protocol.HttpCoreContext
[ERROR] ▒Ҳ▒▒▒org.apache.http.protocol.HttpCoreContext▒▒▒▒▒ļ▒
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project uumai-crawler-core: Compilation failure
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:858)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :uumai-crawler-core
build  install package...

**Comment by kanxg** [comment]
still don't know the issue.  please go to fengchao directory and run : mvn install .    and check the error.

**Comment by gitGksgk** [comment]
great. thanks. adding this to pom.xml works for me.
```
<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpcore</artifactId>
    <version>4.4</version>
</dependency>
```
